package com.researchcenter.services

import android.content.Context
import com.researchcenter.data.models.Intelligence
import com.researchcenter.data.models.NewsArticle
import com.researchcenter.util.Constants
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.net.HttpURLConnection
import java.net.URL

class AiService(private val context: Context? = null) {
    private val json = Json { ignoreUnknownKeys = true }

    suspend fun getArticleExplanation(articleTitle: String, articleContent: String): String = withContext(Dispatchers.IO) {
        try {
            val url = URL("${Constants.BASE_URL}/api/explain")
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "POST"
            connection.doOutput = true
            connection.setRequestProperty("Content-Type", "application/json")

            val body = Json.encodeToString(mapOf("title" to articleTitle, "content" to articleContent))
            connection.outputStream.write(body.toByteArray())

            if (connection.responseCode == HttpURLConnection.HTTP_OK) {
                val response = connection.inputStream.bufferedReader().readText()
                val obj = json.parseToJsonElement(response).jsonObject
                obj["explanation"]?.jsonPrimitive?.content ?: "Error: Intelligence layer connection failed."
            } else {
                "Error: Intelligence layer returned code ${connection.responseCode}"
            }
        } catch (e: Exception) {
            e.printStackTrace()
            "Error: Intelligence layer connection failed."
        }
    }

    suspend fun discoverAISortedNews(): List<NewsArticle> = withContext(Dispatchers.IO) {
        // Load from YOUR AI's intelligence file ONLY
        val aiArticles = try {
            loadAiNewsIntelligence()
        } catch (e: Exception) {
            android.util.Log.e("AiService", "Could not load AI news intelligence", e)
            emptyList()
        }
        
        if (aiArticles.isNotEmpty()) {
            android.util.Log.i("AiService", "✅ Using ${aiArticles.size} AI-sorted articles from YOUR AI")
        } else {
            android.util.Log.w("AiService", "⚠️ No AI news intelligence found. Run export_news_for_app.py")
        }
        
        // Sort by impact score (highest first) and return
        aiArticles.sortedByDescending { it.intelligence?.impact_score ?: 0.0 }
    }
    
    /**
     * Load news intelligence from YOUR AI system
     * This reads from ai_news_intelligence.json generated by NEWS_INTELLIGENCE_AI
     */
    private fun loadAiNewsIntelligence(): List<NewsArticle> {
        // PRIORITY 1: Try to load from assets folder (bundled with app)
        context?.let { ctx ->
            try {
                val inputStream = ctx.assets.open("ai_news_intelligence.json")
                val jsonContent = inputStream.bufferedReader().use { it.readText() }
                val jsonObj = json.parseToJsonElement(jsonContent).jsonObject
                val articlesArray = jsonObj["articles"]?.jsonArray
                
                if (articlesArray != null) {
                    android.util.Log.i("AiService", "✅ Loaded AI news intelligence from assets folder")
                    android.util.Log.i("AiService", "✅ Source: ${jsonObj["source"]?.jsonPrimitive?.content}")
                    
                    return articlesArray.map { element ->
                        val obj = element.jsonObject
                        val intel = obj["intelligence"]?.jsonObject

                        NewsArticle(
                            id = obj["id"]?.jsonPrimitive?.content ?: "",
                            title = obj["title"]?.jsonPrimitive?.content ?: "",
                            source = obj["source"]?.jsonPrimitive?.content ?: "",
                            author = obj["author"]?.jsonPrimitive?.content ?: "",
                            publishedAt = obj["publishedAt"]?.jsonPrimitive?.content ?: "",
                            category = obj["category"]?.jsonPrimitive?.content ?: "",
                            summary = obj["summary"]?.jsonPrimitive?.content ?: "",
                            content = obj["content"]?.jsonPrimitive?.content ?: "",
                            url = obj["url"]?.jsonPrimitive?.content ?: "",
                            intelligence = Intelligence(
                                sentiment = intel?.get("sentiment")?.jsonPrimitive?.content ?: "neutral",
                                confidence = intel?.get("confidence")?.jsonPrimitive?.content ?: "low",
                                asset_tags = intel?.get("asset_tags")?.jsonArray?.map { it.jsonPrimitive.content } ?: emptyList(),
                                impact_score = intel?.get("impact_score")?.jsonPrimitive?.content?.toDoubleOrNull() ?: 0.0
                            )
                        )
                    }
                }
            } catch (e: Exception) {
                android.util.Log.w("AiService", "Could not load from assets: ${e.message}")
            }
        }
        
        // PRIORITY 2: Try external storage locations
        val possibleLocations = listOf(
            java.io.File("/storage/emulated/0/Android/data/com.asc.markets/files/ai_news_intelligence.json"),
            java.io.File("/sdcard/Android/data/com.asc.markets/files/ai_news_intelligence.json"),
            java.io.File("/data/data/com.asc.markets/files/ai_news_intelligence.json"),
            java.io.File("ai_news_intelligence.json")
        )
        
        for (location in possibleLocations) {
            if (location.exists()) {
                try {
                    val jsonContent = location.readText()
                    val jsonObj = json.parseToJsonElement(jsonContent).jsonObject
                    val articlesArray = jsonObj["articles"]?.jsonArray
                    
                    if (articlesArray != null) {
                        android.util.Log.i("AiService", "✅ Loaded AI news intelligence from: ${location.absolutePath}")
                        android.util.Log.i("AiService", "✅ Source: ${jsonObj["source"]?.jsonPrimitive?.content}")
                        
                        return articlesArray.map { element ->
                            val obj = element.jsonObject
                            val intel = obj["intelligence"]?.jsonObject

                            NewsArticle(
                                id = obj["id"]?.jsonPrimitive?.content ?: "",
                                title = obj["title"]?.jsonPrimitive?.content ?: "",
                                source = obj["source"]?.jsonPrimitive?.content ?: "",
                                author = obj["author"]?.jsonPrimitive?.content ?: "",
                                publishedAt = obj["publishedAt"]?.jsonPrimitive?.content ?: "",
                                category = obj["category"]?.jsonPrimitive?.content ?: "",
                                summary = obj["summary"]?.jsonPrimitive?.content ?: "",
                                content = obj["content"]?.jsonPrimitive?.content ?: "",
                                url = obj["url"]?.jsonPrimitive?.content ?: "",
                                intelligence = Intelligence(
                                    sentiment = intel?.get("sentiment")?.jsonPrimitive?.content ?: "neutral",
                                    confidence = intel?.get("confidence")?.jsonPrimitive?.content ?: "low",
                                    asset_tags = intel?.get("asset_tags")?.jsonArray?.map { it.jsonPrimitive.content } ?: emptyList(),
                                    impact_score = intel?.get("impact_score")?.jsonPrimitive?.content?.toDoubleOrNull() ?: 0.0
                                )
                            )
                        }
                    }
                } catch (e: Exception) {
                    android.util.Log.e("AiService", "Failed to parse AI news from ${location.absolutePath}", e)
                }
            }
        }
        
        android.util.Log.w("AiService", "AI news intelligence file not found in any location")
        return emptyList()
    }
}
