package com.researchcenter.services

import android.content.Context
import android.util.Log
import android.util.Xml
import com.researchcenter.data.models.Intelligence
import com.researchcenter.data.models.NewsArticle
import com.researchcenter.util.Constants
import kotlinx.coroutines.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.xmlpull.v1.XmlPullParser
import java.net.HttpURLConnection
import java.net.URL
import java.time.Instant
import java.time.OffsetDateTime
import java.time.LocalDateTime
import java.time.ZonedDateTime
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.util.*

class NewsService(private val context: Context? = null) {
    private val json = Json { ignoreUnknownKeys = true }

    suspend fun fetchAllNews(): List<NewsArticle> = withContext(Dispatchers.IO) {
        // Load from YOUR AI's intelligence file ONLY
        val aiArticlesDeferred = async {
            try {
                loadAiNewsIntelligence()
            } catch (e: Exception) {
                Log.e("NewsService", "Could not load AI news intelligence", e)
                emptyList<NewsArticle>()
            }
        }

        val rssArticlesDeferred = async { fetchAllRssFeeds() }
        
        val aiArticles = aiArticlesDeferred.await()
        val rssArticles = rssArticlesDeferred.await()
        
        if (aiArticles.isNotEmpty()) {
            Log.i("NewsService", "✅ Using ${aiArticles.size} articles from YOUR AI")
        } else {
            Log.w("NewsService", "⚠️ No AI news intelligence found. Run export_news_for_app.py")
        }
        
        // Filter for trading-relevant content only
        val allArticles = (aiArticles + rssArticles)
        val filteredArticles = allArticles.filter { article ->
            isTradingRelevant(article)
        }
        
        Log.i("NewsService", "📊 Filtered ${allArticles.size} articles down to ${filteredArticles.size} trading-relevant articles")
        
        filteredArticles
            .sortedByDescending { it.publishedAt }
            .take(150) // Limit total to 150 as requested
    }
    
    /**
     * Check if article is relevant to forex, crypto, or commodities trading
     */
    private fun isTradingRelevant(article: NewsArticle): Boolean {
        val searchText = "${article.title} ${article.summary} ${article.content}".lowercase()
        
        // Check if article contains exclude keywords (non-trading topics)
        val hasExcludeKeyword = Constants.EXCLUDE_KEYWORDS.any { keyword ->
            searchText.contains(keyword.lowercase())
        }
        
        if (hasExcludeKeyword) {
            // Allow if it also has strong trading keywords (e.g., "regulation" + "forex")
            val hasStrongTradingKeyword = Constants.TRADING_KEYWORDS.take(20).any { keyword ->
                searchText.contains(keyword.lowercase())
            }
            if (!hasStrongTradingKeyword) {
                return false
            }
        }
        
        // Check if article contains any trading keywords
        val hasTradingKeyword = Constants.TRADING_KEYWORDS.any { keyword ->
            searchText.contains(keyword.lowercase())
        }
        
        // AI articles with asset tags are always relevant
        val hasAssetTags = article.intelligence?.asset_tags?.isNotEmpty() == true
        
        return hasTradingKeyword || hasAssetTags
    }
    
    /**
     * Load news intelligence from YOUR AI system
     * This reads from ai_news_intelligence.json generated by NEWS_INTELLIGENCE_AI
     */
    private fun loadAiNewsIntelligence(): List<NewsArticle> {
        // PRIORITY 1: Try to load from assets folder (bundled with app)
        context?.let { ctx ->
            try {
                val inputStream = ctx.assets.open("ai_news_intelligence.json")
                val jsonContent = inputStream.bufferedReader().use { it.readText() }
                val jsonObj = json.parseToJsonElement(jsonContent).jsonObject
                val articlesArray = jsonObj["articles"]?.jsonArray
                
                if (articlesArray != null) {
                    Log.i("NewsService", "✅ Loaded AI news intelligence from assets folder")
                    Log.i("NewsService", "✅ Source: ${jsonObj["source"]?.jsonPrimitive?.content}")
                    Log.i("NewsService", "✅ Timestamp: ${jsonObj["timestamp"]?.jsonPrimitive?.content}")
                    
                    return articlesArray.map { element -> parseArticle(element.jsonObject) }
                }
            } catch (e: Exception) {
                Log.w("NewsService", "Could not load from assets: ${e.message}")
            }
        }
        
        // PRIORITY 2: Try external storage locations
        val possibleLocations = listOf(
            java.io.File("/storage/emulated/0/Android/data/com.asc.markets/files/ai_news_intelligence.json"),
            java.io.File("/sdcard/Android/data/com.asc.markets/files/ai_news_intelligence.json"),
            java.io.File("/data/data/com.asc.markets/files/ai_news_intelligence.json"),
            java.io.File("ai_news_intelligence.json")
        )
        
        for (location in possibleLocations) {
            if (location.exists()) {
                try {
                    val jsonContent = location.readText()
                    val jsonObj = json.parseToJsonElement(jsonContent).jsonObject
                    val articlesArray = jsonObj["articles"]?.jsonArray
                    
                    if (articlesArray != null) {
                        Log.i("NewsService", "✅ Loaded AI news intelligence from: ${location.absolutePath}")
                        Log.i("NewsService", "✅ Source: ${jsonObj["source"]?.jsonPrimitive?.content}")
                        
                        return articlesArray.map { element -> parseArticle(element.jsonObject) }
                    }
                } catch (e: Exception) {
                    Log.e("NewsService", "Failed to parse AI news from ${location.absolutePath}", e)
                }
            }
        }
        
        Log.w("NewsService", "AI news intelligence file not found in any location")
        return emptyList()
    }

    suspend fun searchExternalNews(query: String): List<NewsArticle> = withContext(Dispatchers.IO) {
        try {
            val url = URL("${Constants.BASE_URL}/api/news/search?q=${java.net.URLEncoder.encode(query, "UTF-8")}")
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "GET"
            connection.connectTimeout = 5000
            connection.readTimeout = 5000

            if (connection.responseCode == HttpURLConnection.HTTP_OK) {
                val response = connection.inputStream.bufferedReader().readText()
                val jsonArray = json.parseToJsonElement(response).jsonArray
                jsonArray.map { element -> parseArticle(element.jsonObject) }
            } else {
                emptyList()
            }
        } catch (e: Exception) {
            emptyList()
        }
    }

    suspend fun fetchFullArticleContent(articleId: String): String = withContext(Dispatchers.IO) {
        try {
            val url = URL("${Constants.BASE_URL}/api/news/content/$articleId")
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "GET"
            connection.connectTimeout = 5000
            connection.readTimeout = 5000

            if (connection.responseCode == HttpURLConnection.HTTP_OK) {
                val response = connection.inputStream.bufferedReader().readText()
                val obj = json.parseToJsonElement(response).jsonObject
                obj["content"]?.jsonPrimitive?.content ?: ""
            } else {
                ""
            }
        } catch (e: Exception) {
            ""
        }
    }

    private fun normalizeDate(rawDate: String): String {
        val cleanDate = rawDate.trim()
        if (cleanDate.isEmpty()) return OffsetDateTime.now(java.time.ZoneOffset.UTC).toString()
        
        // 1. Try OffsetDateTime (ISO-8601)
        try {
            return OffsetDateTime.parse(cleanDate).withOffsetSameInstant(java.time.ZoneOffset.UTC).toString()
        } catch (_: Exception) {}

        // 2. Try ZonedDateTime (handles Zone IDs like GMT, EST, BST via RFC_1123)
        try {
            val formatter = DateTimeFormatter.RFC_1123_DATE_TIME.withLocale(Locale.US)
            return ZonedDateTime.parse(cleanDate, formatter).toOffsetDateTime().withOffsetSameInstant(java.time.ZoneOffset.UTC).toString()
        } catch (_: Exception) {}

        // 3. Try parsing with flexible custom pattern list
        val customFormatters = listOf(
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.of("UTC")),
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z").withLocale(Locale.US),
            DateTimeFormatter.ofPattern("EEE, dd MMM yyyy HH:mm:ss Z").withLocale(Locale.US),
            DateTimeFormatter.ofPattern("EEE, dd MMM yyyy HH:mm:ss zzz").withLocale(Locale.US),
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'").withZone(ZoneId.of("UTC"))
        )

        for (formatter in customFormatters) {
            try {
                return ZonedDateTime.parse(cleanDate, formatter).toOffsetDateTime().withOffsetSameInstant(java.time.ZoneOffset.UTC).toString()
            } catch (_: Exception) {}
            try {
                return LocalDateTime.parse(cleanDate, formatter).atOffset(ZoneOffset.UTC).toString()
            } catch (_: Exception) {}
        }

        // 4. Try basic date-only fallback (yyyy-MM-dd)
        try {
            val dateOnlyFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
            return java.time.LocalDate.parse(cleanDate, dateOnlyFormatter).atStartOfDay(ZoneId.of("UTC")).toOffsetDateTime().toString()
        } catch (_: Exception) {}

        // Log warning and return a distant past timestamp so it doesn't clutter top of the feed as "today"
        Log.w("NewsService", "Unable to parse publication date: '$cleanDate', falling back to epoch.")
        return OffsetDateTime.of(1970, 1, 1, 0, 0, 0, 0, java.time.ZoneOffset.UTC).toString()
    }

    suspend fun fetchAllRssFeeds(): List<NewsArticle> = coroutineScope {
        Constants.RSS_FEEDS.flatMap { (category, urls) ->
            urls.map { urlString -> // Increased from 3 to 10 sources per category
                async(Dispatchers.IO) {
                    try {
                        val result = fetchSingleRss(urlString, category)
                        Log.d("NewsService", "Successfully fetched ${result.size} articles from $urlString")
                        result
                    } catch (e: Exception) {
                        Log.e("NewsService", "Failed to fetch RSS from $urlString", e)
                        emptyList<NewsArticle>()
                    }
                }
            }
        }.awaitAll().flatten()
    }

    private fun fetchSingleRss(urlString: String, category: String): List<NewsArticle> {
        val articles = mutableListOf<NewsArticle>()
        val connection = URL(urlString).openConnection() as HttpURLConnection
        connection.setRequestProperty("Cache-Control", "no-cache")
        connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Android) ASC Market News/1.0")
        connection.setRequestProperty("Accept", "application/rss+xml, application/atom+xml, application/xml, text/xml, */*")
        connection.connectTimeout = 5000
        connection.readTimeout = 5000
        connection.instanceFollowRedirects = true
        
        val parser = Xml.newPullParser()
        parser.setInput(connection.inputStream, null)

        var eventType = parser.eventType
        val currentTitle = java.lang.StringBuilder()
        val currentLink = java.lang.StringBuilder()
        val currentPubDate = java.lang.StringBuilder()
        val currentDescription = java.lang.StringBuilder()
        var currentImageUrl: String? = null
        var inItem = false
        var currentTag: String? = null

        while (eventType != XmlPullParser.END_DOCUMENT) {
            val name = parser.name
            when (eventType) {
                XmlPullParser.START_TAG -> {
                    if (name == "item" || name == "entry") {
                        inItem = true
                        currentTitle.setLength(0)
                        currentLink.setLength(0)
                        currentPubDate.setLength(0)
                        currentDescription.setLength(0)
                        currentImageUrl = null
                    } else if (inItem) {
                        currentTag = name
                        if (name == "link") {
                            val href = parser.getAttributeValue(null, "href")
                                ?: parser.getAttributeValue(parser.namespace, "href")
                            if (!href.isNullOrBlank()) {
                                currentLink.setLength(0)
                                currentLink.append(href)
                            }
                        } else if (name == "enclosure" || name == "media:content" || name == "media:thumbnail" || name == "thumbnail") {
                            val urlAttr = parser.getAttributeValue(null, "url")
                                ?: parser.getAttributeValue(parser.namespace, "url")
                            if (!urlAttr.isNullOrBlank()) {
                                currentImageUrl = urlAttr
                            }
                        }
                    }
                }
                XmlPullParser.TEXT, XmlPullParser.CDSECT -> {
                    if (inItem && currentTag != null) {
                        val text = parser.text
                        if (!text.isNullOrBlank()) {
                            when (currentTag) {
                                "title" -> currentTitle.append(text)
                                "link" -> {
                                    if (currentLink.isEmpty()) {
                                        currentLink.append(text)
                                    }
                                }
                                "pubDate", "published", "updated" -> currentPubDate.append(text)
                                "description", "summary", "content", "content:encoded" -> currentDescription.append(text)
                                "id", "guid" -> {
                                    if (currentLink.isEmpty()) {
                                        currentLink.append(text)
                                    }
                                }
                            }
                        }
                    }
                }
                XmlPullParser.END_TAG -> {
                    if (inItem) {
                        currentTag = null
                    }
                    if (name == "item" || name == "entry") {
                        val articleTitle = currentTitle.toString().trim()
                        val articleLink = currentLink.toString().trim()
                        val articleSummary = currentDescription.toString()
                            .replace(Regex("<[^>]*>"), " ")
                            .replace(Regex("\\s+"), " ")
                            .trim()
                        if (articleTitle.isNotBlank() || articleLink.isNotBlank()) {
                            val stableIdSeed = listOf(articleLink, articleTitle, urlString).firstOrNull { it.isNotBlank() }.orEmpty()
                            
                            // Calculate intelligent impact score and extract asset tags
                            val impactScore = calculateImpactScore(articleTitle, articleSummary, category)
                            val assetTags = extractAssetTags(articleTitle, articleSummary)
                            val sentiment = determineSentiment(articleTitle, articleSummary)
                            val confidence = if (impactScore > 60.0) "high" else "low"
                            
                            articles.add(NewsArticle(
                                id = UUID.nameUUIDFromBytes(stableIdSeed.toByteArray()).toString(),
                                title = articleTitle.ifBlank { articleLink },
                                url = articleLink,
                                publishedAt = normalizeDate(currentPubDate.toString().trim()),
                                source = URL(urlString).host.removePrefix("www."),
                                author = "",
                                category = category,
                                summary = articleSummary.take(200),
                                content = articleSummary,
                                imageUrl = currentImageUrl,
                                intelligence = Intelligence(sentiment, confidence, assetTags, impactScore)
                            ))
                        }
                        inItem = false
                        
                        // Limit to 10 articles per source to maintain variety and speed
                        if (articles.size >= 10) return articles
                    }
                }
            }
            eventType = parser.next()
        }
        return articles
    }

    private fun parseArticle(obj: kotlinx.serialization.json.JsonObject): NewsArticle {
        val intel = obj["intelligence"]?.jsonObject
        return NewsArticle(
            id = obj["id"]?.jsonPrimitive?.content ?: "",
            title = obj["title"]?.jsonPrimitive?.content ?: "",
            source = obj["source"]?.jsonPrimitive?.content ?: "",
            author = obj["author"]?.jsonPrimitive?.content ?: "",
            publishedAt = normalizeDate(obj["publishedAt"]?.jsonPrimitive?.content ?: ""),
            category = obj["category"]?.jsonPrimitive?.content ?: "",
            summary = obj["summary"]?.jsonPrimitive?.content ?: "",
            content = obj["content"]?.jsonPrimitive?.content ?: "",
            url = obj["url"]?.jsonPrimitive?.content ?: "",
            imageUrl = obj["imageUrl"]?.jsonPrimitive?.content,
            intelligence = Intelligence(
                sentiment = intel?.get("sentiment")?.jsonPrimitive?.content ?: "neutral",
                confidence = intel?.get("confidence")?.jsonPrimitive?.content ?: "low",
                asset_tags = intel?.get("asset_tags")?.jsonArray?.map { it.jsonPrimitive.content } ?: emptyList(),
                impact_score = intel?.get("impact_score")?.jsonPrimitive?.content?.toDoubleOrNull() ?: 0.0
            )
        )
    }
    
    /**
     * Calculate impact score based on article content and keywords
     * Returns score from 0.0 to 100.0
     */
    private fun calculateImpactScore(title: String, summary: String, category: String): Double {
        val text = "$title $summary".lowercase()
        var score = 0.0
        
        // CRITICAL impact keywords (30-40 points each)
        if (text.contains("rate hike") || text.contains("rate cut") || text.contains("interest rate decision")) score += 40.0
        if (text.contains("emergency") || text.contains("crisis") || text.contains("crash")) score += 35.0
        if (text.contains("war") || text.contains("conflict") || text.contains("invasion")) score += 35.0
        if (text.contains("default") || text.contains("bankruptcy")) score += 30.0
        
        // HIGH impact keywords (20-25 points each)
        if (text.contains("inflation") || text.contains("cpi")) score += 25.0
        if (text.contains("gdp") || text.contains("growth")) score += 20.0
        if (text.contains("employment") || text.contains("nfp") || text.contains("jobs report")) score += 25.0
        if (text.contains("fed") || text.contains("federal reserve") || text.contains("fomc")) score += 25.0
        if (text.contains("ecb") || text.contains("european central bank")) score += 25.0
        if (text.contains("boe") || text.contains("bank of england")) score += 20.0
        if (text.contains("boj") || text.contains("bank of japan")) score += 20.0
        if (text.contains("opec") || text.contains("oil production")) score += 20.0
        
        // MEDIUM impact keywords (10-15 points each)
        if (text.contains("pmi") || text.contains("manufacturing")) score += 15.0
        if (text.contains("retail sales")) score += 15.0
        if (text.contains("trade balance") || text.contains("exports") || text.contains("imports")) score += 12.0
        if (text.contains("unemployment")) score += 15.0
        if (text.contains("consumer confidence")) score += 12.0
        if (text.contains("housing") || text.contains("real estate")) score += 10.0
        if (text.contains("earnings") || text.contains("profit")) score += 10.0
        
        // Currency pairs (10 points)
        val currencies = listOf("eurusd", "gbpusd", "usdjpy", "audusd", "usdcad", "nzdusd", "usdchf")
        if (currencies.any { text.contains(it) }) score += 10.0
        
        // Commodities (10 points)
        if (text.contains("gold") || text.contains("silver")) score += 10.0
        if (text.contains("oil") || text.contains("crude") || text.contains("brent") || text.contains("wti")) score += 10.0
        
        // Crypto (10 points)
        if (text.contains("bitcoin") || text.contains("btc") || text.contains("ethereum") || text.contains("eth")) score += 10.0
        
        // Category boost
        when (category) {
            "central-banks" -> score += 20.0
            "forex" -> score += 15.0
            "commodities" -> score += 12.0
            "crypto" -> score += 10.0
            "macro-trading" -> score += 15.0
        }
        
        // Source credibility boost
        if (title.contains("Federal Reserve") || title.contains("ECB") || title.contains("BOE")) score += 10.0
        
        return score.coerceIn(0.0, 100.0)
    }
    
    /**
     * Extract asset tags from article content
     */
    private fun extractAssetTags(title: String, summary: String): List<String> {
        val text = "$title $summary".uppercase()
        val tags = mutableSetOf<String>()
        
        // Major currencies
        val currencies = listOf("USD", "EUR", "GBP", "JPY", "CHF", "AUD", "NZD", "CAD")
        currencies.forEach { currency ->
            if (text.contains(currency) || text.contains(currency.lowercase())) {
                tags.add(currency)
            }
        }
        
        // Currency pairs
        val pairs = listOf("EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "NZDUSD", "USDCHF", "EURJPY", "GBPJPY")
        pairs.forEach { pair ->
            if (text.contains(pair)) {
                tags.add(pair)
                // Also add individual currencies
                tags.add(pair.substring(0, 3))
                tags.add(pair.substring(3, 6))
            }
        }
        
        // Commodities
        if (text.contains("GOLD") || text.contains("XAU")) tags.add("GOLD")
        if (text.contains("SILVER") || text.contains("XAG")) tags.add("SILVER")
        if (text.contains("OIL") || text.contains("CRUDE") || text.contains("WTI") || text.contains("BRENT")) tags.add("OIL")
        if (text.contains("COPPER")) tags.add("COPPER")
        if (text.contains("NATURAL GAS")) tags.add("GAS")
        
        // Crypto
        if (text.contains("BITCOIN") || text.contains("BTC")) tags.add("BTC")
        if (text.contains("ETHEREUM") || text.contains("ETH")) tags.add("ETH")
        
        // If no specific assets found, add GLOBAL
        if (tags.isEmpty()) {
            tags.add("GLOBAL")
        }
        
        return tags.toList()
    }
    
    /**
     * Determine sentiment from article content
     */
    private fun determineSentiment(title: String, summary: String): String {
        val text = "$title $summary".lowercase()
        
        // Critical/negative keywords
        val criticalKeywords = listOf("crisis", "crash", "collapse", "emergency", "war", "default", "bankruptcy", "recession")
        if (criticalKeywords.any { text.contains(it) }) return "critical"
        
        // Negative keywords
        val negativeKeywords = listOf("decline", "fall", "drop", "weak", "concern", "risk", "threat", "cut", "lower", "down")
        val negativeCount = negativeKeywords.count { text.contains(it) }
        
        // Positive keywords
        val positiveKeywords = listOf("rise", "gain", "growth", "strong", "boost", "increase", "rally", "surge", "up", "higher")
        val positiveCount = positiveKeywords.count { text.contains(it) }
        
        return when {
            negativeCount > positiveCount + 1 -> "negative"
            positiveCount > negativeCount + 1 -> "positive"
            else -> "neutral"
        }
    }
}
